services:
  frontend:
    build: ./frontend
    environment:
      - API_URI="http://backend:5000/api/topics"
    ports:
      - "3000:3000"
    networks:
      - lemoncode-challenge
    depends_on:
      - backend
  backend:
    build: ./backend
    environment:
      - TopicstoreDatabaseSettings__ConnectionString=mongodb://mongodb:27017
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    networks:
      - lemoncode-challenge
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=TopicstoreDb
    ports:
      - "27017:27017"
    networks:
      - lemoncode-challenge
networks:
  lemoncode-challenge:
    name: lemoncode-challenge