services:
  frontend:
    build: ./frontend
    environment:
      - API_URI=http://backend/api/topics
    ports:
      - "8080:3000"
    networks:
      - lemoncode-challenge
    depends_on:
      - backend
  backend:
    build: ./backend
    environment:
      - TopicstoreDatabaseSettings__ConnectionString=mongodb://some-mongo:27017
    ports:
      - "5000:80" # Only needed to send requests directly to the backend
    depends_on:
      - some-mongo
    networks:
      - lemoncode-challenge
  some-mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=TopicstoreDb
    networks:
      - lemoncode-challenge
    volumes:
      - mongodbvol:/data/db
      - ./some-mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017" # Only required if we need to access directly to the database
networks:
  lemoncode-challenge:
    name: lemoncode-challenge
volumes:
  mongodbvol: