services:
  frontend:
    build: ./frontend
    environment:
      - API_URI=http://backend/api/topics
    ports:
      - "8080:3000"
    networks:
      - lemoncode-challenge
    depends_on:
      - backend
  backend:
    build: ./backend
    environment:
      - TopicstoreDatabaseSettings__ConnectionString=mongodb://mongodb:27017
    ports:
      - "5000:80" # only needed to send requests directly to the frontend
    depends_on:
      - mongodb
    networks:
      - lemoncode-challenge
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=TopicstoreDb
    networks:
      - lemoncode-challenge
    volumes:
      - mongodbvol:/data/db
    ports:
      - "27017:27017" # not required
networks:
  lemoncode-challenge:
    name: lemoncode-challenge
volumes:
  mongodbvol: